### ISSUE TITLE
BUG: Server crashes on changelevel after map vetoes

### ISSUE THREAD

**Issue by FlowingSPDG** [shobhit-pathak/MatchZy#180]
My srcds hosted on dathost crashed on changelevel after map vetoes.
I am not sure why that happend, still investigating.

Match JSON
```json
{
  "matchid": 25,
  "clinch_series": false,
  "num_maps": 1,
  "players_per_team": 5,
  "min_players_to_ready": 5,
  "skip_veto": false,
  "map_sides": [
    "knife"
  ],
  "spectators": {
    "players": {
      "76561198072054549": "[Admin]FlowingSPDG"
    }
  },
  "maplist": [
    "de_inferno",
    "de_dust2",
    "de_mirage"
  ],
  "team1": {
    "id": "8",
    "players": {
      "76561198095747156": "sach1",
      "76561198099336489": "Nail",
      "76561198278742909": "yen",
      "76561198328667199": "BAFFOIw",
      "76561198833808598": "山岡士郎"
    },
    "name": "メガメガ"
  },
  "team2": {
    "id": "10",
    "players": {
      "76561198051598754": "StRCaT",
      "76561198132332931": "irori",
      "76561198274569450": "takebath",
      "76561198311476304": "tatsuki",
      "76561198861672944": "L1roA🏰🕛"
    },
    "name": "Chicken Peek"
  },
  "cvars": {
    "matchzy_demo_name_format": "theseus-27_match_25_メガメガ_vs_Chicken Peek",
    "matchzy_demo_upload_url": "MASKED",
    "matchzy_remote_log_header_key": "",
    "matchzy_remote_log_header_value": "",
    "matchzy_remote_log_url": "MASKED",
    "tv_password": "theseus"
  }
}
```

<details><summary>srcds log before crash</summary>

```
Jun 30 07:02:19:  L 06/30/2024 - 07:02:19: World triggered "Match_Start" on "de_mirage"
Jun 30 07:02:19:  L 06/30/2024 - 07:02:19: Team playing "TERRORIST": Chicken Peek
Jun 30 07:02:19:  L 06/30/2024 - 07:02:19: "L1roA🏰🕛<5><[U:1:901407216]><TERRORIST>" triggered "Got_The_Bomb"
Jun 30 07:02:19:  L 06/30/2024 - 07:02:19: MatchStatus: Team "CT" is unset.
Jun 30 07:02:19:  L 06/30/2024 - 07:02:19: MatchStatus: Team playing "TERRORIST": Chicken Peek
Jun 30 07:02:19:  L 06/30/2024 - 07:02:19: MatchStatus: Score: 0:0 on map "de_mirage" RoundsPlayed: 0
Jun 30 07:02:19:  L 06/30/2024 - 07:02:19: Match pause is enabled - mp_pause_match
Jun 30 07:02:19:  'irori': CQ resync (slow_frame), client will discard cmd timing < 21481
Jun 30 07:02:19:  'yen': CQ resync (slow_frame), client will discard cmd timing < 21153
Jun 30 07:02:19:  'L1roA🏰🕛': CQ resync (slow_frame), client will discard cmd timing < 21268
Jun 30 07:02:19:  'BAFFOIw': CQ resync (slow_frame), client will discard cmd timing < 21201
Jun 30 07:02:19:  'sach1': CQ resync (slow_frame), client will discard cmd timing < 20416
Jun 30 07:02:19:  'tatsuki': CQ resync (slow_frame), client will discard cmd timing < 5927
Jun 30 07:02:19:  'StRCaT': CQ resync (slow_frame), client will discard cmd timing < 19205
Jun 30 07:02:19:  'takebath': CQ resync (slow_frame), client will discard cmd timing < 16825
Jun 30 07:02:19:  'Nail': CQ resync (slow_frame), client will discard cmd timing < 11629
Jun 30 07:02:19:  '山岡士郎': CQ resync (slow_frame), client will discard cmd timing < 9015
Jun 30 07:02:19:  'irori': CQ resync (slow_frame), client will discard cmd timing < 21482
Jun 30 07:02:19:  'yen': CQ resync (slow_frame), client will discard cmd timing < 21154
Jun 30 07:02:19:  'L1roA🏰🕛': CQ resync (slow_frame), client will discard cmd timing < 21269
Jun 30 07:02:19:  'BAFFOIw': CQ resync (slow_frame), client will discard cmd timing < 21202
Jun 30 07:02:19:  'sach1': CQ resync (slow_frame), client will discard cmd timing < 20417
Jun 30 07:02:19:  'tatsuki': CQ resync (slow_frame), client will discard cmd timing < 5928
Jun 30 07:02:19:  'StRCaT': CQ resync (slow_frame), client will discard cmd timing < 19206
Jun 30 07:02:19:  'takebath': CQ resync (slow_frame), client will discard cmd timing < 16826
Jun 30 07:02:19:  'Nail': CQ resync (slow_frame), client will discard cmd timing < 11630
Jun 30 07:02:19:  Recording SourceTV replay to MatchZy/theseus-27_match_25_メガメガ_vs_Chicken_Peek.dem...
Jun 30 07:02:19:  playdemo MatchZy/theseus-27_match_25_メガメガ_vs_Chicken_Peek.dem
Jun 30 07:02:19:  '山岡士郎': CQ resync (slow_frame), client will discard cmd timing < 9016
Jun 30 07:02:19:  'takebath': CQ resync (catchup), client will discard cmd timing < 16830
Jun 30 07:02:19:  'L1roA🏰🕛': CQ resync (catchup), client will discard cmd timing < 21277
Jun 30 07:02:19:  'tatsuki': CQ resync (catchup), client will discard cmd timing < 5940
Jun 30 07:02:19:  '山岡士郎': CQ resync (catchup), client will discard cmd timing < 9024
Jun 30 07:02:19:  'BAFFOIw': CQ resync (catchup), client will discard cmd timing < 21209
Jun 30 07:02:19:  'sach1': CQ resync (catchup), client will discard cmd timing < 20425
Jun 30 07:02:19:  'StRCaT': CQ resync (catchup), client will discard cmd timing < 19218
Jun 30 07:02:19:  'Nail': CQ resync (catchup), client will discard cmd timing < 11638
Jun 30 07:02:19:  'yen': CQ resync (catchup), client will discard cmd timing < 21162
Jun 30 07:02:19:  'irori': CQ resync (catchup), client will discard cmd timing < 21490
Jun 30 07:02:20:  autokick is disabled for SourceTV
Jun 30 07:02:25:  [Tick 25952]['山岡士郎' depth=11 (9379..9389) ping=1ms] CQ bloat: removed 6, max: 10, 1 ticks this frame
Jun 30 07:02:25:  [Tick 25953]['山岡士郎' depth=11 (9382..9392) ping=1ms] CQ bloat: removed 2, max: 10, 1 ticks this frame
Jun 30 07:02:30:  autokick is disabled for SourceTV
Jun 30 07:02:37:  [All Chat][yen (318477181)]: .ban mirage
Jun 30 07:02:37:  L 06/30/2024 - 07:02:37: "yen<4><[U:1:318477181]><CT>" say ".ban mirage"
Jun 30 07:02:37:  [MatchZy] [SendEventAsync] Sending Event: map_vetoed for matchId: 25 mapNumber: 0 on MASKED
Jun 30 07:02:37:  [MatchZy] [SendEventAsync] SENDING DATA: {"map_name":"de_mirage","team":"team1","matchid":25,"event":"map_vetoed"}
Jun 30 07:02:37:  [MatchZy] [SendEventAsync] Sending map_vetoed for matchId: 25 mapNumber: 0 successful with status code: OK
Jun 30 07:02:40:  autokick is disabled for SourceTV
Jun 30 07:02:51:  autokick is disabled for SourceTV
Jun 30 07:02:52:  [MatchZy] [SendEventAsync] Sending Event: map_vetoed for matchId: 25 mapNumber: 0 on MASKED
Jun 30 07:02:52:  [MatchZy] [SendEventAsync] SENDING DATA: {"map_name":"de_dust2","team":"team2","matchid":25,"event":"map_vetoed"}
Jun 30 07:02:52:  [MatchZy] [SendEventAsync] Sending Event: map_picked for matchId: 25 mapNumber: 0 on MASKED
Jun 30 07:02:52:  [MatchZy] [SendEventAsync] SENDING DATA: {"map_number":1,"map_name":"de_inferno","team":"team1","matchid":25,"event":"map_picked"}
Jun 30 07:02:52:  [MatchZy] [ExecuteChangedConvars] Execing: matchzy_demo_name_format "theseus-27_match_25_メガメガ_vs_Chicken Peek"
Jun 30 07:02:52:  [MatchZy] [ExecuteChangedConvars] Execing: matchzy_demo_upload_url "MASKED"
Jun 30 07:02:52:  [MatchZy] [ExecuteChangedConvars] Execing: matchzy_remote_log_header_key ""
Jun 30 07:02:52:  [MatchZy] [ExecuteChangedConvars] Execing: matchzy_remote_log_header_value ""
Jun 30 07:02:52:  [MatchZy] [ExecuteChangedConvars] Execing: matchzy_remote_log_url "MASKED"
Jun 30 07:02:52:  [MatchZy] [ExecuteChangedConvars] Execing: tv_password "theseus"
Jun 30 07:02:52:  [MatchZy] [StartWarmup] Starting warmup! Warmup CFG not found in /home/dathost/cs2_linux/game/csgo/cfg/MatchZy/warmup.cfg, using default CFG!
Jun 30 07:02:52:  [All Chat][irori (172067203)]: .ban dust2
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "irori<3><[U:1:172067203]><TERRORIST>" say ".ban dust2"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: Match pause is disabled - mp_unpause_match
Jun 30 07:02:52:  mp_teamname_1 = 
Jun 30 07:02:52:  Unknown command 'mp_radar_showall'!
Jun 30 07:02:52:  Unknown command 'sv_coaching_enabled'!
Jun 30 07:02:52:  Unknown command 'sv_competitive_official_5v5'!
Jun 30 07:02:52:  Unknown command 'sv_grenade_trajectory'!
Jun 30 07:02:52:  SV: Convar 'sv_infinite_ammo' is cheat protected, change ignored.
Jun 30 07:02:52:  Unknown command 'sm_cvar'!
Jun 30 07:02:52:  mp_t_default_primary = 
Jun 30 07:02:52:  "SourceTV<0><BOT><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 432.36 
Jun 30 07:02:52:  "irori<3><[U:1:172067203]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 432.36 
Jun 30 07:02:52:  "yen<4><[U:1:318477181]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 432.36 
Jun 30 07:02:52:  "L1roA🏰🕛<5><[U:1:901407216]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 432.36 
Jun 30 07:02:52:  "BAFFOIw<6><[U:1:368401471]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 432.36 
Jun 30 07:02:52:  "sach1<7><[U:1:135481428]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 432.36 
Jun 30 07:02:52:  "tatsuki<8><[U:1:351210576]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 432.36 
Jun 30 07:02:52:  "StRCaT<9><[U:1:91333026]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 432.36 
Jun 30 07:02:52:  "takebath<10><[U:1:314303722]><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 432.36 
Jun 30 07:02:52:  "Nail<11><[U:1:139070761]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 432.36 
Jun 30 07:02:52:  "山岡士郎<12><[U:1:873542870]><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 432.36 
Jun 30 07:02:52:  Using spawn points configuration 0x0FC590B0
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: Starting Freeze period
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: JSON_BEGIN{
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "name": "round_stats",
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "round_number" : "1",
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "score_t" : "0",
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "score_ct" : "0",
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "map" : "de_mirage",
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "server" : "theseus-27-C",
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "fields" : "             accountid,   team,  money,  kills, deaths,assists,    dmg,    hsp,    kdr,    adr,    mvp,     ef,     ud,     3k,     4k,     5k,clutchk, firstk,pistolk,sniperk, blindk,  bombk,firedmg,uniquek,  dinks,chickenk"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "players" : {
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_0" : "                   0,      0,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_3" : "           172067203,      2,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_4" : "           318477181,      3,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_5" : "           901407216,      2,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_6" : "           368401471,      3,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_7" : "           135481428,      3,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_8" : "           351210576,      2,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_9" : "            91333026,      2,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_10" : "           314303722,      2,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_11" : "           139070761,      3,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: "player_12" : "           873542870,      3,  16000,      0,      0,      0,      0,   0.00,   0.00,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0,      0"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: }}JSON_END
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: World triggered "Match_Start" on "de_mirage"
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: Team playing "TERRORIST": Chicken Peek
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: MatchStatus: Team "CT" is unset.
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: MatchStatus: Team playing "TERRORIST": Chicken Peek
Jun 30 07:02:52:  L 06/30/2024 - 07:02:52: MatchStatus: Score: 0:0 on map "de_mirage" RoundsPlayed: -1
Jun 30 07:02:52:  Unknown command 'cash_team_loser_bonus_shorthanded'!
Jun 30 07:02:52:  'irori': CQ resync (catchup), client will discard cmd timing < 23612
Jun 30 07:02:52:  'yen': CQ resync (catchup), client will discard cmd timing < 23286
Jun 30 07:02:52:  'L1roA🏰🕛': CQ resync (catchup), client will discard cmd timing < 23406
Jun 30 07:02:52:  'BAFFOIw': CQ resync (catchup), client will discard cmd timing < 23336
Jun 30 07:02:52:  'sach1': CQ resync (catchup), client will discard cmd timing < 22552
Jun 30 07:02:52:  'tatsuki': CQ resync (catchup), client will discard cmd timing < 8067
Jun 30 07:02:52:  'StRCaT': CQ resync (catchup), client will discard cmd timing < 21344
Jun 30 07:02:52:  'takebath': CQ resync (catchup), client will discard cmd timing < 18960
Jun 30 07:02:52:  'Nail': CQ resync (catchup), client will discard cmd timing < 13763
Jun 30 07:02:52:  '山岡士郎': CQ resync (catchup), client will discard cmd timing < 11103
Jun 30 07:02:52:  'irori': CQ resync (slow_frame), client will discard cmd timing < 23613
Jun 30 07:02:52:  'yen': CQ resync (slow_frame), client will discard cmd timing < 23287
Jun 30 07:02:52:  'L1roA🏰🕛': CQ resync (slow_frame), client will discard cmd timing < 23407
Jun 30 07:02:52:  'BAFFOIw': CQ resync (slow_frame), client will discard cmd timing < 23337
Jun 30 07:02:52:  'sach1': CQ resync (slow_frame), client will discard cmd timing < 22553
Jun 30 07:02:52:  'tatsuki': CQ resync (slow_frame), client will discard cmd timing < 8068
Jun 30 07:02:52:  'StRCaT': CQ resync (slow_frame), client will discard cmd timing < 21346
Jun 30 07:02:52:  'takebath': CQ resync (slow_frame), client will discard cmd timing < 18961
Jun 30 07:02:52:  'Nail': CQ resync (slow_frame), client will discard cmd timing < 13764
Jun 30 07:02:52:  '山岡士郎': CQ resync (slow_frame), client will discard cmd timing < 11104
Jun 30 07:02:52:  [MatchZy] [SendEventAsync] Sending map_vetoed for matchId: 25 mapNumber: 0 successful with status code: OK
Jun 30 07:02:52:  [MatchZy] [SendEventAsync] Sending map_picked for matchId: 25 mapNumber: 0 successful with status code: OK
Jun 30 07:02:54:  L 06/30/2024 - 07:02:54: World triggered "Warmup_Start"
Jun 30 07:02:58:  SV: Cheat command 'noclip' ignored. Set sv_cheats to 1 enable cheats.
Jun 30 07:02:59:  L 06/30/2024 - 07:02:59: "yen<4><[U:1:318477181]><CT>" [-1627 -1449 -264] killed other "prop_physics_multiplayer<180>" [-1675 -1180 -189] with "usp_silencer"
Jun 30 07:02:59:  L 06/30/2024 - 07:02:59: "sach1<7><[U:1:135481428]><CT>" [-1367 -971 -161] killed other "prop_dynamic<421>" [-1336 -974 -132] with "knife_tactical" (attackerinair)
Jun 30 07:02:59:  [MatchZy] [ChangeMap] Changing map to de_inferno with delay 3
Jun 30 07:03:01:  autokick is disabled for SourceTV
Jun 30 07:03:02:  Changelevel to de_inferno
Jun 30 07:03:02:  changelevel "de_inferno"
Jun 30 07:03:02:  CHostStateMgr::QueueNewRequest( Changelevel (de_inferno), 3 )
Jun 30 07:03:02:  SV:  CNetworkServerService::StartChangeLevel( (no landmark) )
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "irori<3><[U:1:172067203]><TERRORIST>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "irori<3><[U:1:172067203]><TERRORIST>" [1200 -924 -126] committed suicide with "world"
Jun 30 07:03:02:  Client 3 'irori' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "yen<4><[U:1:318477181]><CT>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "yen<4><[U:1:318477181]><CT>" [-1346 -979 -168] committed suicide with "world"
Jun 30 07:03:02:  Client 4 'yen' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "L1roA🏰🕛<5><[U:1:901407216]><TERRORIST>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "L1roA🏰🕛<5><[U:1:901407216]><TERRORIST>" [1233 -1436 -116] committed suicide with "world"
Jun 30 07:03:02:  Client 5 'L1roA🏰🕛' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "BAFFOIw<6><[U:1:368401471]><CT>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "BAFFOIw<6><[U:1:368401471]><CT>" [-1361 -982 -168] committed suicide with "world"
Jun 30 07:03:02:  Client 6 'BAFFOIw' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "sach1<7><[U:1:135481428]><CT>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "sach1<7><[U:1:135481428]><CT>" [-944 -522 -95] committed suicide with "world"
Jun 30 07:03:02:  Client 7 'sach1' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "tatsuki<8><[U:1:351210576]><TERRORIST>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "tatsuki<8><[U:1:351210576]><TERRORIST>" [1296 -352 -168] committed suicide with "world"
Jun 30 07:03:02:  Client 8 'tatsuki' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "StRCaT<9><[U:1:91333026]><TERRORIST>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "StRCaT<9><[U:1:91333026]><TERRORIST>" [1165 240 -195] committed suicide with "world"
Jun 30 07:03:02:  Client 9 'StRCaT' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "takebath<10><[U:1:314303722]><TERRORIST>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "takebath<10><[U:1:314303722]><TERRORIST>" [1125 -895 -261] committed suicide with "world"
Jun 30 07:03:02:  Client 10 'takebath' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "Nail<11><[U:1:139070761]><CT>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "Nail<11><[U:1:139070761]><CT>" [-1227 -947 -168] committed suicide with "world"
Jun 30 07:03:02:  Client 11 'Nail' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "山岡士郎<12><[U:1:873542870]><CT>" disconnected (reason "NETWORK_DISCONNECT_SHUTDOWN")
Jun 30 07:03:02:  L 06/30/2024 - 07:03:02: "山岡士郎<12><[U:1:873542870]><CT>" [-1338 -971 -168] committed suicide with "world"
Jun 30 07:03:02:  Client 12 '山岡士郎' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL
Jun 30 07:03:02:  HostStateRequest::Start(HSR_GAME):  loop(levelload) id(3) addons() desc(Changelevel (de_inferno))
Jun 30 07:03:02:  SwitchToLoop levelload requested:  id [3] addons []
Jun 30 07:03:02:  SV:  IGameSystem::LoopDeactivateAllSystems {
Jun 30 07:03:02:  HO:  IGameSystem::LoopDeactivateAllSystems {
Jun 30 07:03:02:  HO:  } IGameSystem::LoopDeactivateAllSystems done
Jun 30 07:03:02:  SV:  } IGameSystem::LoopDeactivateAllSystems done
Jun 30 07:03:02:  SourceTV[0] shutting down (non-relay) due to server disconnecting game.
Jun 30 07:03:02:  CHLTVServer::Shutdown
Jun 30 07:03:04:  Completed SourceTV demo "MatchZy/theseus-27_match_25_メガメガ_vs_Chicken_Peek.dem":
Jun 30 07:03:04:  	Recording time 148.5,
Jun 30 07:03:04:  	Size 19256543 (2025 per tick).
Jun 30 07:03:04:  	Animation data size 998484 (105 per tick).
Jun 30 07:03:04:  L 06/30/2024 - 07:03:04: "SourceTV<0><BOT><Unassigned>" disconnected (reason "NETWORK_DISCONNECT_HLTVSTOP")
Jun 30 07:03:04:  CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)
Jun 30 07:03:04:  SV:  Server shutting down: NETWORK_DISCONNECT_LOOPDEACTIVATE (55)
Jun 30 07:03:04:  CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)
Jun 30 07:03:04:  --- SERVER EXITED ---
```
</details>

**Comment by Iwhite67** [comment]
https://discord.com/channels/1169549878490304574/1169549994043387935/1253029172360642581

GOTV crash. Recordings start during vetos (which we probably don’t actually want) 

Just try it again or disable GOTV if you can

**Comment by FlowingSPDG** [comment]
@Iwhite67 thanks for the info!

That's strange, I was running 5team tournament and match with one specific team always ran into this issue...

I'll check it further more, I felt like there's something I can fix

**Comment by Iwhite67** [comment]
On my side, this weekend 
For first round, only 1 matchs / 8 was starting without crash
Both crashing.

I play all my lan tournament with manuel veto

**Comment by FlowingSPDG** [comment]
So I guess you ended up disabling GOTV? Or just do vetoes outside of MatchZy and apply?

What I'm guessing is demo name/format, I think I can find something by investigating source codes

**Comment by Iwhite67** [comment]
I not disabled thé gotv because i want keep demo so, I made the vetoes outside of matchzy.

**Comment by shobhit-pathak** [comment]
Hey!

This is a know issue CSTV, it causes server to crash on map change. You will either have to reduce the tv_delay, or completely stop CSTV.
People have been facing such crashes without any plugin as well, so I don't think this is something related to the plugin.

**Comment by Iwhite67** [comment]
74 Maps 0 Crash
crash only with Veto
this is strange

maybe try to have the startrecord to start of map after map change in case we have veto

**Comment by FlowingSPDG** [comment]
@shobhit-pathak oh okay... thanks, I didnt know that.

@Iwhite67 
I guess we can delay when to start recording demo for temporary workaround

https://github.com/shobhit-pathak/MatchZy/blob/91e3c8a12d5b2373a3f390596c9fee7362322d7f/Utility.cs#L607-L630

L617 to L631 or somewhere else

**Comment by shobhit-pathak** [comment]
@FlowingSPDG We don't actually need demo recording in Veto, so I think we should skip start recording if the match is going to be in veto phase

**Comment by Iwhite67** [comment]
This IS a good action :)

**Comment by Iwhite67** [comment]
Hello 
Anyone make a version where the start record IS into live or knife ?
If you make I Can test for you

**Comment by FlowingSPDG** [comment]
@Iwhite67 @shobhit-pathak 
Made PR for testing: #189 . I'll start testing for tournament we will have today!

**Comment by Iwhite67** [comment]
Do You have a release with your edit ? I can test on my side

**Comment by FlowingSPDG** [comment]
@Iwhite67 
You can build by your own by pulling #189 , but I'll build for you if you don't know how

**Comment by Iwhite67** [comment]
i never build a counter strike or C 

i'm main PHP HTML JS

**Comment by Iwhite67** [comment]
> @Iwhite67 
> You can build by your own by pulling #189 , but I'll build for you if you don't know how

Ciao, can you build for me a version for test ?

**Comment by Iwhite67** [comment]
@shobhit-pathak with this fix, he not crashing

**Comment by shobhit-pathak** [comment]
Hey guys!

Thanks for the help, this should be fixed with the 0.8.0 update!

**Comment by aronmgv** [comment]
Still happening o `0.8.6`. I just updated everything to the latest version and if I keep HLTV on (`tv_enable 1`) then after the map vote at the end of a mach server crashes.. If HLTV is disabled (`tv_enable 0`) then changelevel is successful..

Here are the full logs:
```
[Tick 7545]['MacGyver' depth=5 (6923..6927) ping=0ms] CQ bloat: removed 2, max: 4, 1 ticks this frame

[Tick 7747]['MacGyver' empty starved x1=15.6ms ping=0ms] LATE Recv usercmd 7124.  Margin:  2.9ms net +-1 queue =-12.7 total

CHostStateMgr::QueueNewRequest( Changelevel (de_zoo), 4 )

SV:  CNetworkServerService::StartChangeLevel( (no landmark) )

Client 3 'MacGyver' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL

Client 4 'Martin' signon state SIGNONSTATE_FULL -> SIGNONSTATE_CHANGELEVEL

HostStateRequest::Start(HSR_GAME):  loop(levelload) id(4) addons(3101352333) desc(Changelevel (de_zoo))

SwitchToLoop levelload requested:  id [4] addons [3101352333]

SV:  IGameSystem::LoopDeactivateAllSystems {
HO:  IGameSystem::LoopDeactivateAllSystems {
HO:  } IGameSystem::LoopDeactivateAllSystems done
SV:  } IGameSystem::LoopDeactivateAllSystems done
SourceTV[0] shutting down (non-relay) due to server disconnecting game.
CHLTVServer::Shutdown

[#1753661085 UDP steamid:76561197988196786@192.168.255.1:55213 'MacGyver'] closed by peer (2055): NETWORK_DISCONNECT_LOOPDEACTIVATE

[#3252562966 UDP steamid:76561198133856967@85.193.1.223:25150 'Martin'] closed by peer (2055): NETWORK_DISCONNECT_LOOPDEACTIVATE
Completed SourceTV demo "MatchZy/2024-10-23_23-26-37_120_de_nuke_team_MacGyver_vs_team_Martin.dem":Recording time 122.3,Size 4302564 (549 per tick).Animation data size 730476 (93 per tick).

CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)

SV:  Server shutting down: NETWORK_DISCONNECT_LOOPDEACTIVATE (55)

CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()

CPlayerVoiceListener::PostSpawnGroupUnload()
[exited]

[  OK  ] Access console cs2_cw1: Closing console
gamer@caradhras:/srv/cs2$ 
```
